name: Release Image
run-name: ${{ github.event.inputs.tag }}, setLatest ${{ github.event.inputs.setLatest }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Image Version'
        required: true
      setLatest:
        description: 'Set Latest Tag'
        type: boolean
        required: true

jobs:

  on-push:
    name: Release Image
    runs-on: ubuntu-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v4

      - name: Release, Shopware ${{ github.event.inputs.swVersion }}
        uses: ./.github/actions/circleci
        with:
          VERSION: ${{ github.event.inputs.version }}
          SET_LATEST: ${{ github.event.inputs.setLatest }}
          # -------------------------------------------
          CIRCLECI_KEY: ${{ secrets.CIRCLE_CI_TOKEN }}